---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  machineTemplate:
    infrastructureRef:
      kind: LinodeMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      name: ${CLUSTER_NAME}-control-plane
  kubeadmConfigSpec:
    preKubeadmCommands:
      - curl -fsSL https://raw.githubusercontent.com/linode/cluster-api-provider-linode/1de37588527107a250106c0e98ca14d68d12baeb/scripts/pre-kubeadminit.sh | bash -s ${KUBERNETES_VERSION} ${PROXY_CRI_TOOLS_URL:=""} ${PROXY_K8S_RELEASE_URL:=""}
      - hostnamectl set-hostname '{{ ds.meta_data.label }}' && hostname -F /etc/hostname
    clusterConfiguration:
      etcd:
        local:
          dataDir: /var/lib/etcd_data/etcd
          extraArgs:
            quota-backend-bytes: "8589934592"
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      skipPhases:
        - addon/kube-proxy
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ ds.meta_data.label }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ ds.meta_data.label }}'
  version: "${KUBERNETES_VERSION}"
