apiVersion: v1
data:
  cilium-policy.yaml: |-
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "default-cluster-policy"
    spec:
      description: "allow cluster intra cluster traffic"
      endpointSelector: {}
      ingress:
        - fromEntities:
            - cluster
        - fromCIDR:
            - 10.0.0.0/8
            - 192.168.128.0/17
    ---
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "default-external-policy"
    spec:
      description: "allow api server traffic"
      nodeSelector: {}
      ingress:
        - fromEntities:
            - cluster
        - fromCIDR:
            - 10.0.0.0/8
            - 192.168.128.0/17
        - fromEntities:
            - all
          toPorts:
            - ports:
                - port: "${APISERVER_PORT:=6443}"
    ---
    apiVersion: "cilium.io/v2"
    kind: CiliumClusterwideNetworkPolicy
    metadata:
      name: "allow-etcd-policy"
    spec:
      description: "allow etcd traffic"
      nodeSelector: {}
      ingress:
        - fromEntities:
            - all
          toPorts:
            - ports:
              - port: "2379"
              - port: "2380"
kind: ConfigMap
metadata:
  name: ${CLUSTER_NAME}-cilium-policy
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: ${CLUSTER_NAME}-credentials
stringData:
  LINODE_URL: ${LINODE_URL:-"https://api.linode.com"}
  apiToken: ${LINODE_TOKEN}
  dnsToken: ${LINODE_DNS_TOKEN:=${LINODE_TOKEN}}
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-${CLUSTER_NAME}-crs-0
stringData:
  linode-ca.yaml: |-
    kind: Secret
    apiVersion: v1
    metadata:
      name: linode-ca
      namespace: kube-system
    data:
      cacert.pem: ${LINODE_CA_BASE64:=""}
  linode-token-region.yaml: |-
    kind: Secret
    apiVersion: v1
    metadata:
      name: linode-token-region
      namespace: kube-system
    stringData:
      apiToken: ${LINODE_TOKEN}
      region: ${LINODE_REGION}
type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ${CLUSTER_NAME}-cilium
spec:
  chartName: cilium
  clusterSelector:
    matchLabels:
      cni: ${CLUSTER_NAME}-cilium
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://helm.cilium.io/
  valuesTemplate: |-
    bgpControlPlane:
      enabled: true
    policyAuditMode: ${FW_AUDIT_ONLY:=true}
    hostFirewall:
      enabled: true
    extraConfig:
      allow-localhost: policy
    ipam:
      mode: kubernetes
    k8s:
      requireIPv4PodCIDR: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
  version: ${CILIUM_VERSION:=1.18.7}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ${CLUSTER_NAME}-csi-driver-linode
spec:
  chartName: linode-blockstorage-csi-driver
  clusterSelector:
    matchLabels:
      csi: ${CLUSTER_NAME}-linode
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://linode.github.io/linode-blockstorage-csi-driver/
  valuesTemplate: |
    secretRef:
      name: "linode-token-region"
      apiTokenRef: "apiToken"
    csiLinodePlugin:
      env:
        - name: LINODE_URL
          value: ${LINODE_URL:="https://api.linode.com"}
        - name: SSL_CERT_DIR
          value: "/tls"
      volumeMounts:
        - name: cacert
          mountPath: /tls
          readOnly: true
      volumes:
        - name: cacert
          secret:
            secretName: linode-ca
            defaultMode: 420
  version: ${LINODE_CSI_VERSION:=v1.0.9}
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ${CLUSTER_NAME}-linode-cloud-controller-manager
spec:
  chartName: ccm-linode
  clusterSelector:
    matchLabels:
      ccm: ${CLUSTER_NAME}-linode
  namespace: kube-system
  options:
    timeout: 5m
    wait: true
    waitForJobs: true
  repoURL: https://linode.github.io/linode-cloud-controller-manager/
  valuesTemplate: |-
    secretRef:
      name: "linode-token-region"
    image:
      pullPolicy: IfNotPresent
    env:
      - name: LINODE_EXTERNAL_SUBNET
        value: ${LINODE_EXTERNAL_SUBNET:=""}
      - name: LINODE_URL
        value: ${LINODE_URL:="https://api.linode.com"}
      - name: SSL_CERT_DIR
        value: "/tls"
    volumeMounts:
      - name: cacert
        mountPath: /tls
        readOnly: true
    volumes:
      - name: cacert
        secret:
          secretName: linode-ca
          defaultMode: 420
  version: ${LINODE_CCM_VERSION:=v0.9.1}
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: ${CLUSTER_NAME}-cilium-policy
spec:
  clusterSelector:
    matchLabels:
      cluster: ${CLUSTER_NAME}
  resources:
  - kind: ConfigMap
    name: ${CLUSTER_NAME}-cilium-policy
  strategy: ApplyOnce
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: ${CLUSTER_NAME}-crs-0
spec:
  clusterSelector:
    matchLabels:
      crs: ${CLUSTER_NAME}-crs
  resources:
  - kind: Secret
    name: linode-${CLUSTER_NAME}-crs-0
  strategy: ApplyOnce
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: ${CLUSTER_NAME}
spec:
  template:
    spec:
      format: ignition
      ignition:
        containerLinuxConfig:
          additionalConfig: |
            storage:
              links:
                - path: /etc/extensions/kubernetes.raw
                  hard: false
                  target: /opt/extensions/kubernetes/kubernetes-${KUBERNETES_VERSION}-x86-64.raw
              files:
                - path: /opt/extensions/kubernetes/kubernetes-${KUBERNETES_VERSION}-x86-64.raw
                  contents:
                    remote:
                      url: https://github.com/flatcar/sysext-bakery/releases/download/latest/kubernetes-${KUBERNETES_VERSION}-x86-64.raw
            systemd:
              units:
                - name: update-engine.service
                  mask: ${FLATCAR_DISABLE_AUTO_UPDATE:=true}
                - name: locksmithd.service
                  # NOTE: To coordinate the node reboot in this context, we recommend to use Kured.
                  mask: true
                - name: kubeadm.service
                  enabled: true
                  dropins:
                    - name: 10-flatcar.conf
                      contents: |
                        [Unit]
                        Requires=containerd.service coreos-metadata.service
                        After=containerd.service coreos-metadata.service
                        [Service]
                        EnvironmentFile=/run/metadata/flatcar
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
          - name: provider-id
            value: linode://$${COREOS_AKAMAI_INSTANCE_ID}
          name: $${COREOS_AKAMAI_INSTANCE_LABEL}
      preKubeadmCommands:
      - export COREOS_AKAMAI_INSTANCE_LABEL=$${COREOS_AKAMAI_INSTANCE_LABEL}
      - export COREOS_AKAMAI_INSTANCE_ID=$${COREOS_AKAMAI_INSTANCE_ID}
      - export COREOS_AKAMAI_PRIVATE_IPV4_0=$${COREOS_AKAMAI_PRIVATE_IPV4_0}
      - ip addr add "$${COREOS_AKAMAI_PRIVATE_IPV4_0}" dev eth0
      - envsubst < /etc/kubeadm.yml > /etc/kubeadm.yml.tmp
      - mv /etc/kubeadm.yml.tmp /etc/kubeadm.yml
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    ccm: ${CLUSTER_NAME}-linode
    cluster: ${CLUSTER_NAME}
    cni: ${CLUSTER_NAME}-cilium
    crs: ${CLUSTER_NAME}-crs
    csi: ${CLUSTER_NAME}-linode
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - ${K8S_CLUSTER_CIDR:=10.192.0.0/10}
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: ${CLUSTER_NAME}-cp
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: LinodeCluster
    name: ${CLUSTER_NAME}
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: ${CLUSTER_NAME}
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: LinodeMachineTemplate
        name: ${CLUSTER_NAME}
      version: ${KUBERNETES_VERSION}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-cp
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        extraArgs:
        - name: cloud-provider
          value: external
      etcd:
        local:
          dataDir: /var/lib/etcd_data/etcd
          extraArgs:
          - name: quota-backend-bytes
            value: "8589934592"
    format: ignition
    ignition:
      containerLinuxConfig:
        additionalConfig: |
          storage:
            links:
              - path: /etc/extensions/kubernetes.raw
                hard: false
                target: /opt/extensions/kubernetes/kubernetes-${KUBERNETES_VERSION}-x86-64.raw
            files:
              - path: /opt/extensions/kubernetes/kubernetes-${KUBERNETES_VERSION}-x86-64.raw
                contents:
                  remote:
                    url: https://github.com/flatcar/sysext-bakery/releases/download/latest/kubernetes-${KUBERNETES_VERSION}-x86-64.raw
          systemd:
            units:
              - name: update-engine.service
                mask: ${FLATCAR_DISABLE_AUTO_UPDATE:=true}
              - name: locksmithd.service
                # NOTE: To coordinate the node reboot in this context, we recommend to use Kured.
                mask: true
              - name: kubeadm.service
                enabled: true
                dropins:
                  - name: 10-flatcar.conf
                    contents: |
                      [Unit]
                      Requires=containerd.service coreos-metadata.service
                      After=containerd.service coreos-metadata.service
                      [Service]
                      EnvironmentFile=/run/metadata/flatcar
    initConfiguration:
      localAPIEndpoint:
        bindPort: ${APISERVER_PORT:=6443}
      nodeRegistration:
        kubeletExtraArgs:
        - name: provider-id
          value: linode://$${COREOS_AKAMAI_INSTANCE_ID}
        name: $${COREOS_AKAMAI_INSTANCE_LABEL}
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
        - name: provider-id
          value: linode://$${COREOS_AKAMAI_INSTANCE_ID}
        name: $${COREOS_AKAMAI_INSTANCE_LABEL}
    preKubeadmCommands:
    - export COREOS_AKAMAI_INSTANCE_LABEL=$${COREOS_AKAMAI_INSTANCE_LABEL}
    - export COREOS_AKAMAI_INSTANCE_ID=$${COREOS_AKAMAI_INSTANCE_ID}
    - export COREOS_AKAMAI_PRIVATE_IPV4_0=$${COREOS_AKAMAI_PRIVATE_IPV4_0}
    - ip addr add "$${COREOS_AKAMAI_PRIVATE_IPV4_0}" dev eth0
    - envsubst < /etc/kubeadm.yml > /etc/kubeadm.yml.tmp
    - mv /etc/kubeadm.yml.tmp /etc/kubeadm.yml
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: LinodeMachineTemplate
        name: ${CLUSTER_NAME}-cp
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  version: ${KUBERNETES_VERSION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  credentialsRef:
    name: ${CLUSTER_NAME}-credentials
  network:
    apiserverLoadBalancerPort: ${APISERVER_PORT:=6443}
    subnetName: ${SUBNET_NAME:=default}
  region: ${LINODE_REGION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: ${CLUSTER_NAME}
spec:
  template:
    spec:
      authorizedKeys: null
      configuration:
        kernel: linode/direct-disk
      diskEncryption: disabled
      image: ${FLATCAR_IMAGE_NAME}
      interfaces:
      - purpose: public
      networkHelper: false
      region: ${LINODE_REGION}
      type: ${LINODE_MACHINE_TYPE}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-cp
spec:
  template:
    spec:
      authorizedKeys: null
      configuration:
        kernel: linode/direct-disk
      diskEncryption: disabled
      image: ${FLATCAR_IMAGE_NAME}
      interfaces:
      - purpose: public
      networkHelper: false
      region: ${LINODE_REGION}
      type: ${LINODE_CONTROL_PLANE_MACHINE_TYPE}
